### ISSUE TITLE
Mark all conversations - only two are marked then

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#4565]
When I long-press the "mark" icon, "mark all" is shown, but when I press "mark all", only two of my many conversations are marked.

This happens on all my devices running Signal 3.3.3 and I regard this a regression.

**Comment by 2-4601** [comment]
Confirmed on 3.3.1, 3.4.2

**Comment by haffenloher** [comment]
I just tested #4557, it successfully fixes the bug.

**Comment by moxie0** [comment]
should be fixed, would be cool if someone could confirm against master

**Comment by McLoo** [comment]
fix confirmed. 
(3.5.0 is going to be my favorite :grimacing:)

**Comment by Wikinaut** [comment]
I built latest version 3.5.0 and **cannot** confirm that the fix works. 

It is still as reported: When I long-press the "mark" icon, "mark all" is shown, but when I press "mark all", only two of my many conversations are marked.

Or is it, that the problem will only be solved for new received messages ?

**Comment by cascheberg** [comment]
I see this behavior in 3.5.0:
- assume that I have 10 conversations in my list
- long-press one conversation, says 1 selected
- tap "mark all" says 11 (!) selected, but does not highlight the other conversations
- when selecting other conversations manually by tapping them, each time the count still gets increased by one

**Comment by McLoo** [comment]
Funny this totally works in my HTC one S CM 12.1. All convos highlighted. Counter correct. 

On my Z1 compact 5.1.1 xposed the counter is correct, but only the pre-selected-all convos stay highlighted. 

Odd.

**Comment by dcherian** [comment]
I get the second behavior in my moto g 4.4.4 with xposed

**Comment by Wikinaut** [comment]
+1
I confirm, that the new version 6a188248a7d9f6b646ea3144ab0c27d67a0c6ad5 (3.5.1) solves this issue. Thanks.

Question: The first click now selects all converstaions. Shouldn't a second click deselect all ?

**Comment by mcginty** [comment]
@Wikinaut if we did that, I'd prefer to have the icon and description change to indicate it's changed to "select none." Not opposed to that idea, just out of the scope of this fix or how the current iconography works.

**Comment by Wikinaut** [comment]
@mcginty before that fix we had (as a single list item) a tiny "select all" text to click on, which is  apparently dropped in 3.5.1.

The text could be reintroduced, and then a second item "deselect all" - just as an idea:

* select all
* deselect all

(no reply needed)
