### ISSUE TITLE
Country not supported for registration SMS

### ISSUE THREAD

**Issue by gannimo** [WhisperSystems/Signal-Android#5384]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Describe here the issue that you are experiencing.

Registration in Liechtenstein (country code +423) does not work as the initial registration SMS is not received on the device. The registration screen opens, the number can be entered (including the +423 prefix) but the registration then times out, waiting to receive a message. After the time out, when selecting the "call me" option, no call goes through.

I assume this is a limitation on the servers end that does not allow calls/texts to Liechtenstein to go through. I assume that reversing the direction (i.e., the phone calling the Signal server to get the code) would not work as an attacker could spoof his/her phone number.
### Steps to reproduce
- Install Signal on Android phone
- Use Liechtenstein SIM card (country code +423)
- Try to register.

**Actual result:** Registration times out, call fallback does not go through (i.e., no incoming call is received). Interestingly, registration with an earlier phone and the same SIM card/number worked ~1.5 years ago.
**Expected result:** Either a registration text message should be received or after the timeout a call should come in.
### Device info

**Device:** Nexus 5X
**Provider:** Telecom FL
### Link to debug log

Registration fails, so submission of debug log is not possible as the settings cannot be opened.

**Comment by 2-4601** [comment]
Thanks for the well written bug report.
Which app is your default SMS app?
Can you double check that your default SMS app did not receive any Signal related messages ("Your TextSecure verification code: XXX-XXX")

**Comment by gannimo** [comment]
That's an awesome response time, thanks for getting back so quickly!

The default SMS app is the default Android Messenger. Both the Messenger and Whatsapp are installed next to Signal. Neither application did receive a Verification SMS -- regular text messages can be received without problems. It's also puzzling that the fallback call does not go through. Liechtenstein is  a small country and often the provider is not supported.

I'd be happy to provide the full phone number via private message if you want to check the log files.

**Comment by 2-4601** [comment]
You could also try support@whispersystems.org for now. They might have come across this Liechtenstein/Telecom FL combination before.

**Comment by zgrimshell** [comment]
Same issue here. Using the same card on differen phone (huawei p8 lite) doesn't work. On older phone it did. I am from Bosnia and Herzegovina. My number is still registered but I can't even unregister using your website

**Comment by pejakm** [comment]
Same here, Bosnia and Herzegovina (+387). Registration used to work some months ago.

**Comment by anoncoward** [comment]
Same problem here: Czech Republic (+420)

It has worked without problems in the past.

**Comment by riyapenn** [comment]
Country code followed by number of digits in number would be useful.  You can test the number here: https://www.twilio.com/lookup. 

Liechtenstein +423(7moredigits) sample: +4237912345
Bosnia and Herzegovina +387(8moredigits)  sample: +38733123456
Czech Republic +420(9moredigits) sample: +420512345678

**Comment by zgrimshell** [comment]
@riyapenn you want us to give our number to public? I am not sure anyone really should do that ever...

Everyone reported that it worked - why it doesn't work now it is a mystery and giving our numbers will not help (because otherwise it wouldn't even work before if you needed to get my number prior my registration to service).

**Comment by riyapenn** [comment]
_Country code followed by number of digits_, not your number.  # of digits is helpful for troubleshooting/understanding if a user forgot to add an area code/mobile code or if it's an actual issue.  Samples listed are "valid" based on the Twilio link, if you did +4231234567 that would not be "valid"

The countries listed above have total digits >10 and should work, it is likely a provider blocking numbers.  

Andorra does not work because digits are <10, and needs a special case.
Andorra +376(6moredigits) sample: +376812345

**Comment by zgrimshell** [comment]
okay, Bosnia (my provider is mtel with 066 and 065) - +38766123456 and why suddenly multiple providers from different countries would block us...

**Comment by gannimo** [comment]
Yes, the number I used is correct and follows the above mentioned format: +423 (country) 7 (provider) 123456 (actual subscriber)

**Comment by pejakm** [comment]
My number is +387 (0)65 XXX-XXX
If I put leading zero in front of area code, Signal removes it.

**Comment by pejakm** [comment]
> Country code followed by number of digits in number would be useful. You can test the number here: https://www.twilio.com/lookup.

Tested my number and everything is properly recognized.

**Comment by light** [comment]
I'm experiencing this issue or a related issue. I'm not sure of the reason but I'm not receiving the registration SMS. Voice verification doesn't come through either.

Country: France
Provider: Free Mobile
Number format: +33 6 xx xx xx xx

I checked the number with the Twilio lookup tool and it is recognized fine.

**Comment by darkman088** [comment]
Hello,

may I kindly ask what is the status of this issue ? I am having the same problem. Before I was able to register with the callback service, but now I am abroad and I don't want to incur roaming costs.
Can you kindly provide a workaround ? It's quite urgent...

Thank you!

**Comment by gannimo** [comment]
So it appears that the telco provider OWS uses does not support/no longer supports several countries/providers.

The question now is how to mitigate this problem as this turns into a unsatisfactory user experience. In these countries several users have already registered but, when receiving a new device can no longer register their phones. Alternatively, new users cannot register either.

Would it be possible to reverse the direction, i.e., let the signal app send an SMS during the registration phase (or use the phone to call the registration server)?

**Comment by zgrimshell** [comment]
Is there any attention towork on this or was Signal implementation for WhatsApp much more important deal - because WhatsApp works!

So many issues (or being ignored) is kinda sad. If there is something more we can provide please let us now or at least notify us what is wrong/you are working on it.

**Comment by moxie0** [comment]
@zgrimshell Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by martinstingl** [comment]
I was told that the registration process also does not work for South Africa which numbers begin with +27.

**Comment by clementsen** [comment]
+298 (faroe Islands) is not supported either

**Comment by darkman088** [comment]
OK, only complaints for now, but nobody wants to do something in order to get this fixed...

**Comment by 3it-n** [comment]
Hello togehter, update from Liechtenstein: The problem sadly still exists, but our mobile phone provider FL1 is in contact with the support of OWS, which referenced us to this thread/issue.

The technicians at FL1 tested and analyzed the registration process and found out there was neither a try to terminate a SMS nor a call to the target mobile number at the FL1 network. So I think the problem is on OWS side or on SMS/phone-service side used by Signal.
Side note: The registration works when using a land line/POTS phone number in Liechtenstein using the phone call (not SMS).

**Comment by moxie0** [comment]
@3it-n We use Twilio for SMS delivery. It sounds (amazingly) like your telco is actually interested in helping with this. Maybe you could put them in touch with Twilio to try to figure out what's going on?

**Comment by 3it-n** [comment]
@moxie0 I'll forward your message to our telco. Which service is used for the registration phone calls if SMS doesn't work?

**Comment by 3it-n** [comment]
Hi @moxie0, a short Update: After I forwarded your message to our telco, their technicians registered for a evaluation account at Twilio and surprisingly the registration SMS for this service was received.
I've also tested successfully this Twilio registration with my own mobile phone and SMS.

So I think this issue looks like it's on OWS side, not at Twilio.

**Comment by L3g3ntt** [comment]
same issue here; apparently OWS is not interested in solving it though.

**Comment by 3it-n** [comment]
Hi @moxie0. Can you tell me which service is used for placing the phone calls? Is this also done by Twilio? 

Just a thought: Are there any filters used on OWS servers to limit triggering the services of Twilio to avoid misuse?

**Comment by moxie0** [comment]
@3it-n Also Twilio. The only server side limits are rate limits, which the client should tell you if you've hit.  I just verified that +387 is enabled for both SMS and Voice on Twilio, and our Twilio bill says that messages are "delivered" to that country code.

Would you be willing to email me (moxie+github@whispersystems.org) with your phone number, and we can do some real-time debugging?

**Comment by pejakm** [comment]
@moxie0 @zgrimshell I can confirm that Signal now succesfully registers my number (+387) from Bosnia&Herzegovina.

**Comment by moxie0** [comment]
@pejakm Hmm, we haven't changed anything. It was either on the carrier or twilio's end.

**Comment by LaMpiR** [comment]
Any news on this? Is there a different way to verify a number since the Bosnia doesn't work?

**Comment by jeremymasters** [comment]
@LaMpiR I thought that @pejakm just mentioned that Bosnia _does_ work?

**Comment by pejakm** [comment]
@LaMpiR I was able to register with 065 number (*haloo* network).

**Comment by LaMpiR** [comment]
Last night, two numbers from 065 mtel were not able to register. Sms confirmation problem, sms simple didnt come. One number received today a confirmation, after few tries. Second one didnt.

Numerous tries last night and today and somehow it came through.

It actually came through when I enter 065 instead of 65. It was corrected anyway but that made it happen.

Will try later on as well and post back.

**Comment by LaMpiR** [comment]
Just tested for 20th time. Not working 065 mtel in Bosnia.

**Comment by L3g3ntt** [comment]
@moxie0 3it-n is talking about not being able to register with a Liechtenstein number (+423). And so am I.
And again: Twilio is working perfectly, so the question perhaps is if a rate limit is not allowing the registration SMS to be terminated.
I sent you an e-mail with my mobile number, so you can test and debug anytime.

**Comment by moxie0** [comment]
I think registration for Liechtenstein should work now. The issues with Bosnia look like telco stuff to me, @LaMpiR do the voice calls not come through either?

**Comment by 3it-n** [comment]
Hi @moxie0. Thanks for you work, we've already tested it successfully, Liechtenstein is now part of the game!

**Comment by LaMpiR** [comment]
@moxie0 no, calls ever came. When I got lucky to activate it on one card, tried many times before with the call option as well, nothing.

**Comment by LaMpiR** [comment]
I got an email on 23.12. that I should update the app and try from Whisper System but it is still not working in Bosnia. Tried three different phones, all Mtel +387 65 numbers. Any success?

**Comment by gannimo** [comment]
@moxie0 yes, Liechtenstein works now. I verified this last week. Sorry for the slow reply, I was traveling. I'd be happy to close the (Liechtenstein) issue -- thanks a lot for your efforts!

Would it make sense to open another support/registration issue on a per-country basis for the other countries that are not working?

**Comment by 2-4601** [comment]
@gannimo I think it would help to keep track of the countries on one shared list. It's pretty tedious to find out the countries from the various comments on this issue :)
We could for example use the very first post on this issue (your report) and edit it to contain an updated list of unsupported countries.

**Comment by gannimo** [comment]
@2-4601 sure, please go ahead. I'd also be fine closing this issue as my problem has been solved.

**Comment by LaMpiR** [comment]
Would be very helpful if we could get some info about the status of the current bugs? I am looking forward to using it, and a sms verification not working is a bit absurd :)

**Comment by 2-4601** [comment]
@LaMpiR I updated the first comment, as far as I could tell your case is the only one not working?

**Comment by riyapenn** [comment]
https://github.com/WhisperSystems/Signal-Android/issues/5384#issuecomment-204058004
https://github.com/WhisperSystems/Signal-Android/issues/5850
https://github.com/WhisperSystems/Signal-Android/issues/5291

- [ ] Andorra +376(6moredigits) sample: +376812345
- [ ] Bosnia and Herzegovina +387(8moredigits) sample: +38733123456
- [ ] Czech Republic +420(9moredigits) sample: +420512345678
- [ ] New Caledonia +687(6moredigits) workaround: add 0 after the number to create a total of 10 digits, but then user can only be found if 0 is also stored in the contact list
- [ ] Greenland: +299(9moredigits)
- [ ] Faroe Islands: +298(6moredigits) workaround: add 0 after the number to create a total of 10 digits, but then user can only be found if 0 is also stored in the contact list


**There are quite a few other special case scenarios (thought not necessarily requested by users)**

- [ ] Niue +683(4digitnumber)
- [ ] Tokelau +690(4digitnumber)
- [ ] Ascension Island +247(4digitnumber)
- [ ] Equatorial Guinea +24007(4digitnumber)
- [ ] French Polynesia +68922(4digitnumber)
- [ ] Chad +235250(4digitnumber)
- [ ] Solomon Islands (landline): +677(5digitnumber)
- [ ] Cook Islands Format +682(5digitnumber)
- [ ] St. Helena and Tristan da Cunha +290 (4/5digitnumber) 4 digits according to wiki, but twillio has it with 5 digits
- [ ] Samoa: +685(5digitnumber)
- [ ] Suriname: +597(6digitnumber)

**Just a reminder, there are also country specific formatting limitations for some users:**
- [ ] Argentina, add 9 after the country code
- [ ] Brazil, add the city code after the country code
- [ ] Mexico, add 1 after the country code
- [ ] UK, remove the leading 0 after the country code

**Comment by 2-4601** [comment]
Oh my, seems really complicated :thinking: 
Are these all countries that cannot register to Signal or just don't work with Signal messaging (after registering) because the formatting is non-standard/weird?

**Comment by 2-4601** [comment]
Thanks for the detailed list @riyapenn 
Decided to move this into it's own issue #6027 so it doesn't look like @gannimo has to maintain the list :)
The new issue will only track registration problems that are caused by number schemes. Not issues with sending and receiving messages that are caused by unorthodox number formatting nor censorship.

**Comment by juancn** [comment]
I'm having trouble from Argentina (+54 prefix) from iOS. 
Mobile numbers here are weird, if you call from Argentina, the number is:
`<area code>`-15-`<number>` e.g. 11 15 5555 1234
But if you call from abroad, the format is:
`<country code>`-9-`<area code>` - `<number>` e.g. + 54 9 11 5555 1234

I tried both formats with no luck

**Comment by michaelkirk** [comment]
> I'm having trouble from Argentina (+54 prefix) from iOS.

@juancn - to clarify, the trouble that you're having is that you enter your SMS number, yet you do not receive the verification code SMS, right?

And you are entering the number like this?

<img width="559" alt="screen shot 2017-12-14 at 3 42 18 pm" src="https://user-images.githubusercontent.com/217057/34013399-61b52b4a-e0e5-11e7-9083-16e5b71e1485.png">

**Comment by belag** [comment]
Verification is not working on Serbia Telenor again..(+381-63xxx +381-69xxxx etc)
No SMS or call comes through.

**Comment by stavreski** [comment]
Same here in Macedonia. I'm using Telekom (T-Mobile) +389-75xxxxxx. It used to work on my iPhone Signal app, now I'm not receiving SMS confirmation codes. Calls as well. :(

Help!

**Comment by cgniksic** [comment]
Not working in Montenegro +382 (069)

**Comment by SolKuczala** [comment]
i have the same problem than Juancn with my android, from Argentina

**Comment by riyapenn-signal** [comment]
@SolKuczala Make sure the number you are registering with is a total of 13 digits. It will be +549 (+ 10 digit number). If you can not receive the SMS, then you can tap on 'Call me' to receive a phone call with the verification code. It is possible your provider is blocking the SMS or calls. Feel free to contact support@signal.org for troubleshooting.
